account_seed_version = [3, "u8"]
payment_to_treasure = 5000
holder_msg_size = 950
evm_steps_min = 500
evm_steps_last_iteration_max = 1
gas_limit_multiplier_no_chainid = 1000
storage_entries_in_contract_account = [64, "usize"]
treasury_pool_count = 128
treasury_pool_seed = "treasury_pool"
