program_id = "53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io"
operators_whitelist = [
    "9kPRbbwKL5SYELF4cZqWWFmP88QkKys51DoaUBx8eK73",
    "BMp6gEnveANdvSvspESJUrNczuHz1GF5UQKjVLCkAZih",
    "CVAimMqtcmSUCV4RLZSJAreDpEd7JEZmrvCVj85yaRzZ",
    "5mszzfV23zRfcAdn9d7kmW6Qn57SGkpGywyqyVCVc817",
    "AdtXr9yGAsTokY75WernsmQdcBPu2LE2Bsh8Nx3ApbbR",
    "2k8NURTZ8xd1qD2JhujP2MjxkLgLHUmwpXP8FNSP7ntd",
    "EkEBZJmw4uKfvruf3c6EFJeWeAY3rev3hRsp2S4BDV3M",
    "9LosHtRuxtFYtj2bJfvkcZpDywtdktpAabRQ7hCQasmt",
    "FHYUtkDhNaMdaKzP2y7ZXmy6HtiKz7uahz19CPUkjeiD",
    "3NqgsSRfjpmDfzRH4PLKrzBvMc8MgFXgU58Yy8n41KF5",
    "8HStt6KLgRY8CBNmDjwMTZhCFrXeVrEgVp3jTS4gaRYR",
    "V6fr3EgLUYFSGgzPBxTnhrieeAratBX46AGvAtmQ2Xe",
    "7r5GAh4SDhBwxg98vT86Q8sA8c9zEgJduSWWCV1y48V",
    "GwUnjJs6i7TKGjy71PvFpGN7yu9xqA8Cs1oyV4zSVPvq",
    "EdSEh9UxXjbrrHLrH5manpxfXi7HxzkAMDAotPC5DggQ",
    "9s7umnvnGqT1nvrCgzvBwWFyaaYABj64LxiBpjAayLiv",
    "2Ma3MxGpKmk2KPbp631bNhm2NcSMU6oxFgtj2FfzkiBF",
    "2v3dnQQaBALRmaQ1Jr7GbCVagTqEBKHPZ65b4nAmdDmN",
    "47dYMgKdKxRGuGBpjH58eGuj1n4FXC6v4QTcpCSaVC2c",
    "5dyQQATyk4yga4f4m8BCrUF1jdfGQ1mShV4ezFLxyCqW",
    "7C6iuRYzEJEwe878X2TeMDoCHPEw85ZhaxapNEBuqwL9",
    "82YcsM5eN83trdhdShGUF4crAC4CGgFJ7EWd2vnGiSsb",
    "A3CEBvqJPPgHPARxzUQUafHXC4iU6x4iZzNudJ1Tks4z",
    "AezpxgT4Qbo1pB9cLgBzzET7V2t7yK2ZrJrhDTCwxac9",
    "CXJy6dzL8kAazo5jhBf8MuW17nJ8dW23EfzPmqTJ6P5H",
    "DPRfsB8HQrJZM5g3B74rqZSmvtJn41PavhKBjmCRb45R",
    "EbkUFw2EQkG85ua4sQy54Y6c988j7zkSAjkD6gRUTA3u",
    "F4nLmDy62mhYiY4gGmRXDYpdFM4mLrm9t5YLpqTDMBz5",
    "GHGLwKXzo2fAtLAVNJisP7wNyCRWBcmHEzCD36UcutW1",
    "GZ3vKajaDjxFkiczL4g6as3qhMg7tdMgrMrpuApGWF8D",
    "eXiURdoUQ4JpUysAevcTPiLMdWwG8q6mRAmice5Kioh",
]

[chain.neon]
id = 111
token = "HPsV9Deocecw3GeZv1FkAPNCBRfuVyfw9MMwjwRe1xaU"

[chain.sol]
id = 112
token = "So11111111111111111111111111111111111111112"

[chain.abc]
id = 113
token = "HPsV9Deocecw3GeZv1FkAPNCBRfuVyfw9MMwjwRe1xaU"

[chain.def]
id = 114
token = "HPsV9Deocecw3GeZv1FkAPNCBRfuVyfw9MMwjwRe1xaU"