chain_id = 111
operators_whitelist = [
    "9kPRbbwKL5SYELF4cZqWWFmP88QkKys51DoaUBx8eK73",
    "BMp6gEnveANdvSvspESJUrNczuHz1GF5UQKjVLCkAZih",
    "CVAimMqtcmSUCV4RLZSJAreDpEd7JEZmrvCVj85yaRzZ",
    "5mszzfV23zRfcAdn9d7kmW6Qn57SGkpGywyqyVCVc817",
    "AdtXr9yGAsTokY75WernsmQdcBPu2LE2Bsh8Nx3ApbbR",
    "2k8NURTZ8xd1qD2JhujP2MjxkLgLHUmwpXP8FNSP7ntd",
    "EkEBZJmw4uKfvruf3c6EFJeWeAY3rev3hRsp2S4BDV3M",
    "9LosHtRuxtFYtj2bJfvkcZpDywtdktpAabRQ7hCQasmt",
    "FHYUtkDhNaMdaKzP2y7ZXmy6HtiKz7uahz19CPUkjeiD",
    "3NqgsSRfjpmDfzRH4PLKrzBvMc8MgFXgU58Yy8n41KF5",
    "8HStt6KLgRY8CBNmDjwMTZhCFrXeVrEgVp3jTS4gaRYR",
    "V6fr3EgLUYFSGgzPBxTnhrieeAratBX46AGvAtmQ2Xe",
    "7r5GAh4SDhBwxg98vT86Q8sA8c9zEgJduSWWCV1y48V",
    "GwUnjJs6i7TKGjy71PvFpGN7yu9xqA8Cs1oyV4zSVPvq",
    "EdSEh9UxXjbrrHLrH5manpxfXi7HxzkAMDAotPC5DggQ",
    "9s7umnvnGqT1nvrCgzvBwWFyaaYABj64LxiBpjAayLiv",
    "2Ma3MxGpKmk2KPbp631bNhm2NcSMU6oxFgtj2FfzkiBF",
    "2v3dnQQaBALRmaQ1Jr7GbCVagTqEBKHPZ65b4nAmdDmN",
    "47dYMgKdKxRGuGBpjH58eGuj1n4FXC6v4QTcpCSaVC2c",
    "5dyQQATyk4yga4f4m8BCrUF1jdfGQ1mShV4ezFLxyCqW",
    "7C6iuRYzEJEwe878X2TeMDoCHPEw85ZhaxapNEBuqwL9",
    "82YcsM5eN83trdhdShGUF4crAC4CGgFJ7EWd2vnGiSsb",
    "A3CEBvqJPPgHPARxzUQUafHXC4iU6x4iZzNudJ1Tks4z",
    "AezpxgT4Qbo1pB9cLgBzzET7V2t7yK2ZrJrhDTCwxac9",
    "CXJy6dzL8kAazo5jhBf8MuW17nJ8dW23EfzPmqTJ6P5H",
    "DPRfsB8HQrJZM5g3B74rqZSmvtJn41PavhKBjmCRb45R",
    "EbkUFw2EQkG85ua4sQy54Y6c988j7zkSAjkD6gRUTA3u",
    "F4nLmDy62mhYiY4gGmRXDYpdFM4mLrm9t5YLpqTDMBz5",
    "GHGLwKXzo2fAtLAVNJisP7wNyCRWBcmHEzCD36UcutW1",
    "GZ3vKajaDjxFkiczL4g6as3qhMg7tdMgrMrpuApGWF8D",
    "eXiURdoUQ4JpUysAevcTPiLMdWwG8q6mRAmice5Kioh",
]

[token_mint]
neon_token_mint = "EjLGfD8mpxKLwGDi8AiTisAbGtWWM2L3htkJ6MpvS8Hk"
decimals = 9

[collateral_pool_base]
neon_pool_base = "pBuoBvc4jeWcRvYABZaxtLZFfT2rnXW7G8ixLYc15bQ"
prefix = "collateral_seed_"
main_balance_seed = "treasury_pool"
neon_pool_count = 10

[account_whitelists]
neon_permission_allowance_token = "B2m2PGZQuZzaVMkeH8fLR8EbefiEy64ybCxVuzhx6RD1"
neon_permission_denial_token = "D73ziEn1qS4egcMfADTZJnnn5XCENdcrDDcwAnSEvqGX"
neon_minimal_client_allowance_balance = "0"
neon_minimal_contract_allowance_balance = "0"
