chain_id = 245022934
operators_whitelist = [
    "NeonPQFrw5stVvs1rFLDxALWUBDCnSPsWBP83RfNUKK",
    "GYt9w8MaXztDLhhsxmQr7Ar9FJ6MmaFwav7qBrxZKwhd",
    "65g8N1ZTkWNo953PuWcYvnNsqC7EmbDvtRtgp4bmVT4S",
    "EcRUp3ah4CfAkew6UALfjHdzxZNQkWo767YTKK4H5HhM",
    "AbCp2zzd3qcA14uBosLdaYWUEJMxMBb2sfkzhDWURszW",
    "5qT6Wh3FyY3jJdqcf39ZXXMRN3zc2wEqQAKuakkXBZdG",
    "GfvDvxwjngmDNHfy6vpSk7MsRXzcfFtjCPe9jFuRJLih",
    "DnM2coxi7qu3AEKhN6Qk9mGQEAL1mAzeRmQyyWvQhcNX",
    "GJi4s1ALwrcGrdgAEZ6o2H6w4Movs2KwtFmZfZmt3eDN",
    "5atJcg4d8TAqAjRynWXHCsPs7gbJgqWHYvVkERMnkRQs",
    "EWhrrtA5fv9YtcHPWmYMK8VBS1V1t5s4GTspxPPuXGPZ",
    "45wTPXC8VvqrW3rymWVmrWsF4LisNnzJTnniU9LnRHJH",
    "CbdwxL2txJCGnYbEAMohfdcm7fUZWL87aCLjsqSpyKzR",
    "273fHsaWQwDcXEuzJ9yS2wu4VvZsRxc5fuK2oSmNY513",
    "DC1M1eD1ZYdUYWVy1GKr372p1H7jJVTSAjzmgaPgFSHW",
    "6KZLqnACXZrZ5JuPCm55m7YWesTNnCbGGDr3RysxhhCS",
    "ACzzSM2caeYueQCn9x8HpMaqoEkYFiigxikaxqe5iNcE",
    "5S7onsbfUXRMgrDX7R2Lp7v24z21kBoRVKeyEnAjGcdL",
    "GFa3c88L9NdkSKnwNyBCUC6juHSXPifat5r1u7PxZQQD",
    "EybjaSYmBcAzvfEtPk3fL1xtrTLvBSYAZ3CuSzu2nXrp",
    "HhDDQWtnDufThqK2tf1YfYbZzSouhErtuzRx8y4thsei",
    "GdkdE3husHhFzdt37MzWh8HPBi2MXRJHCZHkSCNLfTuD",
    "U1opJYxJV4zuQKuFwoXW45dLRKpNo7EkJjguRqWvy9s",
    "BAkYYQNNziqW2HmxQDSCU57JmqW2cmmfdeqmduhk5gYm",
    "KKjaYCyjXAfwuugaMSpgE2widgB6GUajD5Pze8NQptm",
    "EpuLUGJdSA9Lhe6pNxfXEAfBo6eGEuTVJjRQY93ZHdqP",
    "5i2XZkeLZuQKuns8aKDAKMnp2UCtKU9H4tYT4npXax4g",
    "DHGV5vXk9HpE7BRbCPmruFdq3wXBHqYBq4b8AP5vD6pN",
    "BhiWQ67L79bqAvefzEw9en3hmodXdyCR5a5qgAPT7EQU",
    "9GprgQo6pJ4hhT9YGAUeFsViE7YRaK8dttswYeN1tN6G",
    "AvCNVjRx8m9mycvhn87mbVbbi3YrgVJjV2fAFu9rsgk1",
    "HhbDiF6v8aPywr2gUU9AdQ2PX9W73ARc9bVQjEc931sm",
    "DJoMJKcksFEtjvjE7xkLKrT5kcVcniQR9s4C6ZuD3UNk",
    "HAFHnF4X2xkNjUTrXEw1FWKRF4kXdmn9wN61VA6kkuz7",
    "DAf6MQokeK7KdUVXCC6REX9DNwssAXEgt4Ri3vczT6HV",
    "2fNHBqeArUXSz32DfXQC4AmiiTNuo7mLRVWVY8tPZKKF",
    "9WYXXkQ8CSJd4t2Q3HT4auQVJyE7B86jodpqrDpw2XDE",
    "5p6SzmyEPBgySFSLZoSF5CXnUU7GPpf67f6NjbfhdKBH",
    "4NxuZhiHzeL6pENbPpP4GuHadHHu1jSDGkz5MDBW1tMR",
    "2uyrreutuU7s9FjgV3ptsX9UhNiboi1GwxXunXiVwmcH",
    "7VDZcJqZv2sUW5XmVtyGqwpFpTpbaz88ppGjyBbtUAZ3",
    "ALLcid9tKeSHumLZgmYoaFnPTUgTVo9i63quf65v5j6Y",
    "EPCPeqVgi8TP91zhYrzK9pz9mwnTsqxdH6VBXBnXoPjr",
    "AtvULAyvCMXSPeBa3oAM4y9J18ncW4VKMDtSibYrBA6T",
    "DL1qqtqcZrijd8WrfvwZMBe8stUCSntjVxWHfVF4dfjC",
    "Gct64jtD72WUFjgjd1Lz65e6Rc2Edkt4QuEkb82xujZd",
    "9cpMJQ5i1tDWTh4Ya2shJAXEM7AygHbYfgQvYTB13MX",
    "9hgaCEx6YepnXuJaRzQHoGovdx3bi988cvnQR48tX2xw",
    "EzCyipR6EKS494dWuz1hcxkoQR1b6dBAU7QGZCksYvvb",
    "qMpnDCegWrzx8MGy63ikvvgwQxuubmHza3QaGiLTgGL",
    "6fRgRzU2caLjeFGcA9brkZudwRc8xczN85NsEBVLrfXK",
    "ECER7q7cNcW1HTVpoKpfcNQh2NQ1WwusKvkk7CA5bYjB",
    "9db14BTMSmHLkUQBce9SB8fstLV84AxwaTnAS3JTFkmn",
    "aiRv8rmf4wXeQVoBRnCEcJEYoPzU4ovQVECo173VZeH",
    "GZmJa2gdvZWFiqEvnCthB5VBb5W5KmsbJEqSztUPxUwf",
    "ACpyy8i6q2fxncDvAbCBy7KMVkdkAgg6z6GfB547BqKm",
    "GCAkNpk69x9dPo9oapYeWx9ieviUJxvK8HsEzV7pceU6",
    "9awwTAdwtrdhdfLF4GQvLJNnABLaJJ3CsfHFCcDyY4We",
    "6X5KLLfCoCXwFpr5bC1WC7D4zkpgKfTmvPQSwfGgnfTT",
    "CByLkvBRZya16Eu8xkrLsYyZH8ZnTW8htLCcr853ctKS",
    "HRsFSCFntWWLkBeKW18zJqfjpCEPpYhkmjCKPPpgaJPY",
    "2s3P34fEa82ti9kaAV2kvy9qfUoxRtQACBTuWVLLFiE8",
    "828sbDu437wr6nvuMq7YBCGcSX7MKwCNHQyaPLRonhDP",
    "8wXUvU388JosWK5i9zmWJP8dsxLmtsGCUp47nS9Yso8w",
    "GtnuSjoxvNW2gaBxfzq8bevizmtjXN7agrZ1UANSQjVU",
    "8fhCxVtM4ZjLeHS1ZPbR4BxDNSyEB15yEVKEar5jtPpr",
    "HDXcAQ1u4NSPy2ChMdPxAhs8P9ThQUSdmn9HqB1nBhuP",
    "EvirCRx2sAtVUqD2a9V8meZ9ngitTu8PWJyQAS69oq7s",
    "B69SvafJ2QEdCuJV1GCYhj3kPh8pbkQvyWPdPnu3zpWS",
    "AeFeRPZqsAZFVYon3g2fA8XX27ZYBnhrxck2n4DZnhp",
    "HTJEfXkk831BJFZN4AFjccQ221hD4T6XJK8w8GAtParV",
    "4WsWuDPhYhUS22y5Qdd1MBxnCbaFUxpAFMWRpbzq2myi",
    "57EFBcdD2pS2vvJLJQ3akkBcHeiKaVAMQo3HSencBc1f",
    "9eLjvq2tNe9LbC5NJPX4FnxTGZx7rbMJbCQLnNJ38gXu",
    "55HWUJ7gosLDmSSN5j3gShxzEGChPPPH7XMiZG1kwrRV",
    "2gfGMAG49SCetiWX6MwGsoU2yBdeUWCW4sNAUhAvtNA2",
    "EEnvyNZ4skLEdiSzwwB7vWvs2zyGiZovhQdotzvhSe28",
    "94EF39friJjbqh8qg8iXbrKJmxn2na4AFVje3oF21RJL",
    "WktLUp6oFoEuKahctGtYd7fpFyJtJFHUpAg7sKBZTwh",
    "8iQEvMf3JovnDf9qLPAjGYe7VLRWLC25mmQy4cy1om9R",
    "5J5pfy5YGMxP74VRDw2TiQMY2Y8uHLPoaNEe2S5gAtUA",
    "5GRKYKDwhsjARx1NUUUpyEun3ANGtAmRCYXLC4yyVWid",
    "BpAwX5vNLA8QzCCgZHdQSqmj9hW3d7NT16BMKQ7fYZi8",
    "GYBbprmeaoaUCn6QwPS9SntwaCWDrvmxepLusaWUZ645",
    "7gJC2kTpKhx6xEifMdTiPFazKHgK6YS5yg3cdRF6voAi",
    "611DYLZezGmseNXaHLSkff4M1XyCEFyG8KfXLHWabYho",
    "8doqAzcXQzhQ5DkkEvgyP8rRPDksyiYsxQ7XHRZd1j78",
    "2nXcLrurvktTpfyiYLwDPvC2qpjoGogV9tmfEFSSM5Y5",
    "B9qQpxNybcanEs7a7KCMU3bMNzawjatHPxhRrFkie5Gh",
    "3qondpAPfgU2zcuV4uRsEKcvvej4QqDcEyfo8nXUUHy9",
    "7fbJXVk9VDy7NCe8hNY3xQ5u6xoH4ySNtZeoLd1XnygQ",
    "2MRXHrcosRmQdvTqnfo9CTg4J7F1Ayp9cU997TY5Vvjm",
    "3eJkcWY3nje9TYbGfte1n4gRGZrkKrJwVSX1oEUPknNr",
    "8GcekU711bxqLgwtayRebgUPLPQexbUAvoTfr2i4SmS5",
    "8v5o8z7ahTmqz5pBGpvAojCKLyzPzwJPr6oiHgATKcZB",
    "7otqBd9uK2WdLvwJ4eTTbQjwo1Fn9Xi9sfSB1D5qumCp",
    "4D8WFwMx47zN7hkQHvikxvQWiREpdU5Pt2RVoQKHAUif",
    "BchQnzicxp9LCj7zuxFMi4LyjMq1j7NyzYKWqHxoJQhf",
    "HJb8tSRy3Ca3XPoWUTxgGUHD13jVSGFy97HAr8PDytLm",
    "4SxbPp4zCYQPw9KfVB2k86oLZHDdqobGfyjVEiPv8Ebc",
    "3tQU51uNa4pjEdTpZgb2K1wL18cG4dgiyCbmyUpniNZ2",
    "24sMd9Vfejwu5QTqyu8ig9GbAuEYrbP1yLL6w12Actbg",
    "28jZMYDL4edWKAqY93bhCD3b88bbCfDpVd2eGMrAUdmV",
    "2GcoTj7fehpce8ohnUzira1c36DNUz7kYaUPtU4cBphr",
    "2W6cuQHb14NFZzmhKdgXojRVLRBCfUfVBVrmqThL5RQy",
    "2myNtgxRzLeKCpy87LCzHKVYRg9eZHnsVU8P5hQePjmz",
    "2ttrXT1FXy41gv6D1TL8rM48pYhaaftmZEmH1gDiXRH4",
    "3F7A9b26m5CTxo7GjHCteZzPRcWZ861hhDxra4RQ7QVq",
    "3N2tWvKpak7Geev6trzZz1NjJ5x6j1xPGWotYkN1D4DR",
    "3vLW8KH8RxnfYwVbMGt2K5bDMEvLbfq3gvPvhiVVBf2d",
    "4D8HhpP8tH66vP2co4CDNoptsWKtK9HKBcxfGtxxG3UF",
    "4K8x8sSzipxPwFeYYPSGHS9Ut1Dhb1chpi12khoV8gD3",
    "4QJv95TqLnk5WgtyMHwbVfd5nkWBWNnzHhwnLo64R2yK",
    "4YbVg7KM3zrirMjTWzGWcdUqs8FZ7iFGyKPM73e9RebT",
    "4dMKZcobR8jKUCfFCFhvRvhWp7bbyPkFdr9791RmCUMs",
    "4vFYzx6TcbYkK6YmGun9sX2fgA23HqpCrwB8H87YFovG",
    "5AZq2rLWNryMx3V2bPBJx2TaqERQZ6TYJS5y2SXJacpz",
    "5GVyVAs6nyP52ykqFdgbw1Hg8ujdLHspT3BTmEvtEUds",
    "5ogCSE2JMnro2g6T1VNsoDirHCJ4Cs696yqQUMZULqbm",
    "5y1hmjnA6ZfhFEQvmostj27NgzAzwEYMatMtSCTvhMAo",
    "67hg4ypkiec21B6MTQBpEDgmgiUWxVChJJnnPH9VfvBr",
    "6GoLiLLHHojKX3p6abLcr5tZLWHPjY9Tto7HPMJLKNjd",
    "7MqePDdydYafZPFJHEzCyKozsfF9WcjzpkmcSQrjzMeV",
    "7RdGYyumpRR9P3j95wuxAUMXteofJgf7QMrEyfgCvkhZ",
    "7W3JpG7W7LSfNwaSKSfBjrsiXSEA3NfftCtMbzKfmT5a",
    "7Wjjv7qUrTUtSGAzHiKGJ8owQyvBUsZrBqJ3VXyzRqUg",
    "7XcURKJwFncTEAez2JoF4QvUu4NhwAx8kXbst7xoWH2Y",
    "7dwKdt7PrxYXYUghQikWuVEAXQCQNR2GZkVE6Avy6om7",
    "7mDZPmFVexfzvmwZLDFEfZhjMRZb3fkbS1A7kQJdSGMP",
    "7miMarGfr1Lg4K7p7VeqBo6FcoxDvtkCFAq4DccCB5fe",
    "7vqyTxrXqKdkC24waXgQ5fjkbsmmS6jDFJkwXdLwgmHb",
    "82qeXAbW2uGW9dgkB8ZUB3YskVCdAL3whcnrdEUKz9jC",
    "8491unozSmyxf4ZSu5dimvS64SqQkDEyPYZg2EFatUkB",
    "8KF4fbXf2Uvh1TvZDntZgZRpp54cx2dqt9psxp3MG25b",
    "8WNTMrfwGvXoYvWty6cUu5uwtkaJZK5p4ZMhQbpzE6cf",
    "8gBQE261gQ3n57ZNLRFZBnwioVRGGZSeUyP6d1YTnBoL",
    "8hEJhd2aFYHJ78KLQ9ZVifCuJFNXHcGw7ZqKBqyxYFb2",
    "8xaVYRxo4zHzfiT4GJT1GT87gnRewnPdpVPegwU1XFvT",
    "8xjQnntwvxAcoj1ZpYfUNx1Esw4dAsqXqopcB5MRCqbj",
    "9AjXFcUjBSQi4pzrTUpM95qx5iDRJs4jmnFoC3Q2fzgA",
    "9VCz3j7yqWRSJJ1t2QFq7p2jC5ACz6kyCQSL6RfZthLM",
    "9YqDfGcXYsjjnKjLxM8riqyVBCQ8cXwZQANJ7o8FbayQ",
    "9YvgYrqD2N6gYkvvJsS6JFGytyyFPdVXXgR8HDobHKjn",
    "9ZsVcwcYaB8sis9gP9ThRbegynFEXDd3iZXKhw2qKuyh",
    "9ozhQxVPn2Yp4KH1xE3aHk2SJPaT2ZgXXxQHWZp6wStt",
    "A5W3bry1yB6D6r7ULii6hcNrBwvk1p1eKDhpYkRNjSJt",
    "ANRLMwz2w6UNsqv2XtJwXBPaKqkLx87qfCazNdVqrMqy",
    "ASCg47DcdxqGJFRTpsguiNKAKaAAzvm53NAZWeeoQZHh",
    "Az1C8kC6tj29kGH1R5zFmELQNG1SgeVxH4mhazxsdeEh",
    "BJ4rSMPGWraCbWKRzJ1cWHjTiA6rwcdH9qaqFLTpRDE6",
    "BJEUWTgYZKF84CpqnJUzsVNiE1AcBzoFSXnygrQzbEpr",
    "BZALYiHSyuTCBLRYHtuCHgitKosYdiny9F1URmHJJeM8",
    "BdKxWwkNixHEr3a1rHVkk3nUWmDhZH5wDwjPUt8ypFn8",
    "BojgvBit1itbYtFqjHj8U156gAFuMxzhoi3SdENm7wkf",
    "BsKBTYyyYfVm5cJaHXRZewYF7dcU18aNGF9EbLJ2y2eo",
    "CAj18bAnpzdztLsfr4gyWEp6h9MkJiV4dbv1v9BvVBMS",
    "CFYKi7La1CMvt5AHuXCRSLuDXPmmquG3PiuDjXNW28GC",
    "CQSuv6PCmEdsTyQifLQMxdsUycVq8AiCDajMX3K4LanU",
    "CeWMupuCm4riTaLjXUYTuyM2B9aK4uHzhdn4rw3JNQ1z",
    "CfptrCmZwxcq2fCtYiXvPLAqjwUVKB8Q6X458A58FKvU",
    "ChTccDRYrD5KLQuWcB36M2N9TK6a7X8kGNNpasaJj5Z4",
    "Chs8S271STS1fAK5usAv1cm33TPG5CXPJ9sR9ZihPbek",
    "CtaSd3XXGLL4rSQkdDHqNQ5QRcug5wJcEHy8z79SJYfE",
    "CwUKVVBRpYvkUKHmMy4hbA8xcuuHpLGBdQMrFM3HN1A7",
    "D8fthUX6FEQFSNyjNyzz9Ur3JEdAyxhxHdYPhpbnUfPn",
    "D9FTTazjDdcfq2PKS5pta54qG67drBW6WgRfkQhwanPZ",
    "DcBCRtSUjjXtQNodJT9Rxa8Ht4kJiHSSMpAy5AUb2Cet",
    "Def5ZPMers4gzdUY6ZAPodbZQaTd3qA2se2nHmy4e6f5",
    "DfN8EJsmvDBJKXNh6DBJEKW93tjtnECRLZnfUGMCBDmA",
    "DmJK19vDxU9Wk7sUP8jfPBqtEHqpL5Zm2QCDGRkiUoP1",
    "Dsf9GdLiRu9c8RifX6ez7PNgzyVCdCr46j45d43EWWCy",
    "E1jjUuEVwW5ahc1JcFzMhTjpFDtLrTjDrFrof4xUGMMZ",
    "EBz2KeBDEvn5VeNjEdK7jTkoJcxmQ7xe6tpKdgrqs7Dk",
    "EX4cBrK1RG2VvQZTBPstzKiUEKzmMXTDLjW9TktYRWn7",
    "EaFm5sQT62QbPVod2y31CrQMjjWTZ98aEJVau7cnpv8X",
    "EqNKVHV3Us5SydS7q1Z2q7wX98EcAM1eFrn7akHTP2BN",
    "FCYLQBV9KBgGf2tNTvAAzXBFDifsNWksirAJJy9ydekY",
    "FEDsVtc6wqpdt5NMef2ifWC3ALvgvM7zn6edbg7HCjUq",
    "FPWChzhUc6RyMFGJmjHJJxRVBedzVphPW2U1wXdfAUsh",
    "FVcPXCSGXsRxrAyRxJeMGoruCCCRFvUK2iZ2zg6mNzyK",
    "Fga2EVoafbTXa7Hqgomniu7PkkMAsS3rDqjQ3adW5Wq6",
    "FqZ2oh66gkjq4bZhrE13xAVupgu8htsPb14maceLwtCx",
    "G11VM4ByWp59vtaPTRsSbdW51mtuZERhZRR6eQGQ5Bnd",
    "G9A4Kk1KdErtDuzgLPeZiS9sweaFKL8bKNzqWkkWq61p",
    "GDFt2hbk1TqQSR8EDoGopwZCiGZ6DkLEVFb3Frqrk9LS",
    "GcsXSmP8qZu5nzFnXwJVAqoTCXKFMFVQDYsrD6y9PmRs",
    "Gn6Lqb9Mz7aVLcRxy24Sy3LkUuteGMChZnffLBwwFCVh",
    "GspVkx5kqdzLFme2iMyXewaAbyts9gX3A3KG3F69FUZq",
    "HCk27Njw7WBoUb5VdB2roBHhQWsWKPx1mRcsrswsAJv8",
    "HEd4cn14Ydi6zSCgppMTgDbJWjZCWeSV4k53SXzm2c7W",
    "HNYjknV3REYYtoZEj1u4wBXUZ9RAZViKhpiiRCqSe1Dp",
    "HdWCgBtULzQk8A5wkg7zdLfa9o3zFKGPUZoDKgJ99xJ7",
    "Hm6rz56MCMDw4AwYSne28LC68XP3H1qxKZU62Zz4AsiM",
    "HvtEBos21fFoKJYi81g49bshfZrjPGr3H8AA8zev2V4X",
    "KaZ8ncr6d2v1pmeCttdGQwGL8M5ERHHF7QrTo99c2qQ",
    "LovQMvFwW8XfkMekAPtx12LTk6rWV4HFFBpubhijYDC",
    "TwnGXeK48oDeA8EseiQKDaBReVC73FJWgG9MCpR219R",
    "UEmRps4SXrtiH5zifdvoizCsneYAS6BkxnJ9oh9Pyvu",
    "c5mzVC8RMH424vhYXkt4GFfgZ1wT9GxsuuHiZvxu2QX",
    "ooFGEiW5FGTLb5CTxbDRd6tQKsgfpAF68eipRKQU268",
    "v53q1eoz9dYQ2czTjsspYy2Jkg5xTDRJd8MMyrRLdUF",
]

[token_mint]
neon_token_mint = "NeonTjSjsuo3rexg9o6vHuMXw62f9V7zvmu8M8Zut44"
decimals = 9
