version: "3"

services:
  set_single_acct_permission:
    container_name: set_single_acct_permission
    image: neonlabsorg/evm_loader:${REVISION:-latest}
    env_file:
      - ./config/${CONFIG_NAME}/.env
    environment:
      OPERATION: ${OPERATION}
      ACCOUNT_TYPE: ${ACCOUNT_TYPE}
      NEON_ETH_ADDRESS: ${NEON_ETH_ADDRESS}
      MINT_AUTHORITY_FILE: /opt/config/mint_authority_keypair.json # DO NOT CHANGE! Edit corresponding line in volumes section instead
    volumes:
      - ./config/${CONFIG_NAME}/:/opt/config/
      - ~/.config/solana/id.json:/root/.config/solana/id.json
    entrypoint: >
      ./set_single_acct_permission.sh
      
  set_many_accts_permission:
    container_name: set_many_accts_permission
    image: neonlabsorg/evm_loader:${REVISION:-latest}
    env_file:
      - ./config/${CONFIG_NAME}/.env
    environment:
      OPERATION: ${OPERATION}
      ACCOUNT_TYPE: ${ACCOUNT_TYPE}
      ADDRESS_LIST_FILE: /opt/config/address_list
      MINT_AUTHORITY_FILE: /opt/config/mint_authority_keypair.json
    volumes:
      - ./config/${CONFIG_NAME}/:/opt/config/
      - ~/.config/solana/id.json:/root/.config/solana/id.json
    entrypoint: >
      ./set_many_accts_permission.sh
